Repository jenkins-x-plugins/jx-release-version, pull requests merged in 2019-11, with the labels that each got.

#44 test: cleanup the unit tests and improve the assert messages
  jenkins-x.yml
  main.go
  main_test.go
  test-resources/helm/Chart.yaml
Labels: size/L

#45 test: comment out the test which fails because of the meta-pipeline bumping the version
  main_test.go
Labels: size/XS

#38 feat: Add support for cmake
  main.go
  main_test.go
  test-resources/cmake/CMakeLists.txt
Labels: approved, lgtm, size/M

#41 feat: add a flag for setting the version template vs scanning files
  README.md
  main.go
Labels: approved, lgtm, size/M

#46 feat: add minor argument
  adapters/githubclient.go
  domain/model.go
  go.sum
  main.go
  main_test.go
  mocks/GitClient.go
Labels: approved, lgtm, ok-to-test, size/L

#37 feat: Added setup.py support
  main.go
  main_test.go
  test-resources/python/nested/setup.py
  test-resources/python/one_line/setup.py
  test-resources/python/standard/setup.py
Labels: approved, lgtm, size/L
