Repository jenkins-x-plugins/jx-release-version, pull requests merged in 2021-05, with the labels that each got.

#81 chore: move image from gcr to ghcr
  .jx/updatebot.yaml
  .lighthouse/jenkins-x/release.yaml
  README.md
  action.yml
  main.go
Labels: approved, size/S

#85 chore: lets allow git config to be set using flags or env vars to avo…
  README.md
  go.mod
  go.sum
  main.go
  pkg/tag/tag.go
Labels: approved, size/L

#86 fix: from-file strategy now fallback to the next file
  .gitignore
  pkg/strategy/fromfile/automake.go
  pkg/strategy/fromfile/cmake.go
  pkg/strategy/fromfile/from_file.go
  pkg/strategy/fromfile/from_file_test.go
  pkg/strategy/fromfile/gradle.go
  pkg/strategy/fromfile/helm_chart.go
  pkg/strategy/fromfile/js_package.go
  pkg/strategy/fromfile/makefile.go
  pkg/strategy/fromfile/maven_pom.go
  pkg/strategy/fromfile/testdata/gradle/build.gradle
  pkg/strategy/fromfile/testdata/gradle/gradle.properties
Labels: approved, size/L

#87 chore: improve readme
  README.md
Labels: approved, size/M
