Repository jenkins-x-plugins/jx-release-version, pull requests merged in 2021-03, with the labels that each got.

#68 feat: add gradle.properties support
  strategy/fromfile/from_file_test.go
  strategy/fromfile/gradle.go
  strategy/fromfile/testdata/gradle.properties
Labels: approved, ok-to-test, size/S

#69 fix: commits iteration
  strategy/semantic/semantic.go
Labels: approved, size/XS

#70 chore: add ability to strip prerelease information from the version
  README.md
  main.go
  strategy/semantic/semantic.go
Labels: approved, size/S
