Repository jenkins-x-plugins/jx-release-version, pull requests merged in 2021-04, with the labels that each got.

#71 feat: lets optionally allow a flag to create and push a tag when generating the next release version
  go.mod
  main.go
  pkg/strategy/auto/auto.go
  pkg/strategy/auto/auto_test.go
  pkg/strategy/auto/testdata/.gitignore
  pkg/strategy/auto/testdata/empty-git-repo.tar.gz
  pkg/strategy/auto/testdata/git-repo.tar.gz
  pkg/strategy/fromfile/automake.go
  pkg/strategy/fromfile/cmake.go
  pkg/strategy/fromfile/from_file.go
  pkg/strategy/fromfile/from_file_test.go
  pkg/strategy/fromfile/gradle.go
  pkg/strategy/fromfile/helm_chart.go
  pkg/strategy/fromfile/helm_chart_test.go
  pkg/strategy/fromfile/js_package.go
  pkg/strategy/fromfile/makefile.go
  pkg/strategy/fromfile/maven_pom.go
  pkg/strategy/fromfile/python.go
  pkg/strategy/fromfile/python_test.go
  pkg/strategy/fromfile/testdata/CMakeLists.txt
  pkg/strategy/fromfile/testdata/Chart.yaml
  pkg/strategy/fromfile/testdata/Makefile
  pkg/strategy/fromfile/testdata/build.gradle
  pkg/strategy/fromfile/testdata/build.gradle.kts
  pkg/strategy/fromfile/testdata/configure.ac
  pkg/strategy/fromfile/testdata/gradle.properties
  pkg/strategy/fromfile/testdata/package.json
  pkg/strategy/fromfile/testdata/pom.xml
  pkg/strategy/fromfile/testdata/setup-nested.py
  pkg/strategy/fromfile/testdata/setup-oneline.py
  pkg/strategy/fromfile/testdata/setup.py
  pkg/strategy/fromtag/from_tag.go
  pkg/strategy/fromtag/from_tag_test.go
  pkg/strategy/fromtag/testdata/.gitignore
  pkg/strategy/fromtag/testdata/git-repo.tar.gz
  pkg/strategy/increment/increment.go
  pkg/strategy/increment/increment_test.go
  pkg/strategy/manual/manual.go
  pkg/strategy/semantic/semantic.go
  pkg/strategy/semantic/semantic_test.go
  pkg/strategy/semantic/testdata/.gitignore
  pkg/strategy/semantic/testdata/git-repo.tar.gz
  pkg/strategy/strategy.go
  pkg/tag/tag.go
  pkg/tag/tag_test.go
Labels: approved, lgtm, size/L

#73 chore: use a single import for go-git
  go.mod
  go.sum
  pkg/tag/tag.go
  pkg/tag/tag_test.go
Labels: approved, size/M

#74 fix: handle repos with merge commits
  .gitignore
  pkg/strategy/auto/auto_test.go
  pkg/strategy/auto/testdata/.gitignore
  pkg/strategy/auto/testdata/repo-with-merge-commit.tar.gz
  pkg/strategy/semantic/semantic.go
Labels: approved, size/M

#75 feat: if mvn is installed, use 'help:evaluate' to extract project.version
  pkg/strategy/fromfile/maven_pom.go
Labels: approved, size/M

#76 fix: turning log level down to warn when fallback is available
  pkg/strategy/fromfile/maven_pom.go
Labels: approved, size/XS

#77 fix: support repos with no semver tags
  pkg/strategy/auto/auto.go
  pkg/strategy/fromtag/from_tag.go
Labels: approved, size/S

#79 chore: wrap errors
  go.mod
  pkg/strategy/auto/auto.go
  pkg/strategy/fromfile/from_file.go
  pkg/strategy/fromtag/from_tag.go
  pkg/strategy/semantic/semantic.go
  pkg/tag/tag.go
Labels: approved, size/M

#80 fix: commits iteration for semantic strategy
  pkg/strategy/semantic/semantic.go
Labels: approved, size/M
