Repository jenkins-x-plugins/jx-release-version, pull requests merged in 2021-01, with the labels that each got.

#56 feat: add support for semantic release using conventional commits
  go.mod
  go.sum
  main.go
  semrel/semrel.go
Labels: approved, lgtm, ok-to-test, size/XXL

#58 feat: read USE_SEMANTIC_RELEASE env var
  main.go
Labels: approved, lgtm, ok-to-test, size/S

#57 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/L, updatebot
